---
- hosts: localhost
  connection: local
  vars:
    git_dotfiles_repo: "https://gitlab.com/martin.goerz/dotfiles.git"
    # Alias to manage dotfiles
    git_dotfiles_alias: "config"
    # Directory for dotfiles
    git_dotfiles_dir: "{{ ansible_env.HOME }}"
    # Directory for .git/ of dotfiles repository
    git_dotfiles_dir_dot_git: "{{ ansible_env.HOME }}/.dotfiles/"
    # Directory for backup files
    git_dotfiles_dir_backup: "{{ ansible_env.HOME }}/.dotfiles_bak"
    # File in which alias gets defined, empty string to not set it
    git_dotfiles_alias_file: "{{ ansible_env.HOME }}/.bash_aliases"
  roles:
    - role: workstation

